// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCewogEgOC0UJSmjs2JeK8Rp1HumJBSTv0',
    appId: '1:999922079161:web:a6d2c1482444edcc4d5268',
    messagingSenderId: '999922079161',
    projectId: 'doit-10140',
    authDomain: 'doit-10140.firebaseapp.com',
    storageBucket: 'doit-10140.firebasestorage.app',
    measurementId: 'G-H8ZG8K684E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV9H5C8rqODMgF24XxfI7kehhjaPnCHFM',
    appId: '1:999922079161:android:4cde4990f94c4bde4d5268',
    messagingSenderId: '999922079161',
    projectId: 'doit-10140',
    storageBucket: 'doit-10140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9_1gvIC7rAZrtGbpUEh-WClOH_qsuOVU',
    appId: '1:999922079161:ios:cbbf3b90c10bd1a04d5268',
    messagingSenderId: '999922079161',
    projectId: 'doit-10140',
    storageBucket: 'doit-10140.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9_1gvIC7rAZrtGbpUEh-WClOH_qsuOVU',
    appId: '1:999922079161:ios:cbbf3b90c10bd1a04d5268',
    messagingSenderId: '999922079161',
    projectId: 'doit-10140',
    storageBucket: 'doit-10140.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCewogEgOC0UJSmjs2JeK8Rp1HumJBSTv0',
    appId: '1:999922079161:web:9b90b8d14402d69d4d5268',
    messagingSenderId: '999922079161',
    projectId: 'doit-10140',
    authDomain: 'doit-10140.firebaseapp.com',
    storageBucket: 'doit-10140.firebasestorage.app',
    measurementId: 'G-73FMCYDQL5',
  );
}
